
package relojdigital;

import javax.swing.SpinnerNumberModel;

public class AlarmaPanel extends javax.swing.JPanel {

    /**
     * Creates new form Alarma
     */
    public AlarmaPanel() {
        initComponents();
        configurarSpinnerMinutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLHora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSpHora = new javax.swing.JSpinner();
        jSpminutos = new javax.swing.JSpinner();
        jChActiva = new javax.swing.JCheckBox();

        jLHora.setText("Hora");

        jLabel1.setText("Minutos");

        jSpminutos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jSpminutosComponentShown(evt);
            }
        });

        jChActiva.setText("Activa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jSpHora, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jSpminutos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLHora)
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jChActiva)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSpminutos, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jSpHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jChActiva)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSpminutosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jSpminutosComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpminutosComponentShown
     private void configurarSpinnerMinutos() {
        // Configuración del rango del Spinner para los minutos
        SpinnerNumberModel modelMinutos = new SpinnerNumberModel(0, 0, 59, 1);
        jSpminutos.setModel(modelMinutos);
    }
     
    private void configurarSpinnerHora() {
        // Configuración del rango del Spinner para la hora
        SpinnerNumberModel modelHora = new SpinnerNumberModel(0, 0, 23, 1);
        jSpHora.setModel(modelHora);
    }
    
    public Alarma getSelectValue() {
        int horaAlarma  = (int)jSpHora.getValue();
        int minutosAlarma =(int)jSpminutos.getValue();
        boolean activa = jChActiva.isSelected();
        return new Alarma(horaAlarma, minutosAlarma, activa);
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jChActiva;
    private javax.swing.JLabel jLHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner jSpHora;
    private javax.swing.JSpinner jSpminutos;
    // End of variables declaration//GEN-END:variables
}
